application: turkanet
version: 1
runtime: python
api_version: 1

derived_file_type: # http://googleappengine.blogspot.com/2010/06/app-engine-sdk-135-released-with-new.html
- python_precompiled

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
