application: TODO
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /upload
  secure: always
  login: admin
  script: main.py

- url: /cron
  secure: always
  login: admin
  script: main.py

- url: /_ah/queue/(.*)
  secure: always
  login: admin
  script: main.py

- url: /.*
  script: main.py
